apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.workbench.pvc.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.workbench.name }}
    app.kubernetes.io/managed-by: Helm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.workbench.pvc.size }}
  {{- if .Values.workbench.pvc.storageClassName }}
  storageClassName: {{ .Values.workbench.pvc.storageClassName }}
  {{- end }}
