---
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: qwen3-reranker
  annotations:
    serving.kserve.io/stop: "false"
    security.opendatahub.io/enable-auth: "false"
    openshift.io/description: ""
    openshift.io/display-name: qwen3-reranker
    serving.kserve.io/deploymentMode: RawDeployment
    opendatahub.io/model-type: generative
  labels:
    opendatahub.io/dashboard: "true"
spec:
  predictor:
    automountServiceAccountToken: false
    deploymentStrategy:
      type: RollingUpdate
    maxReplicas: 1
    minReplicas: 1
    model:
      args:
        - "--model=/mnt/models"
        - "--runner=pooling"
        - "--convert=classify"
        - "--dtype=float32"
        - "--max-model-len=1024"
        - "--served-model-name=qwen3-reranker"
        - "--max-num-seqs=8"
        - "--max-num-batched-tokens=1024"
      env:
        - name: VLLM_CPU_KVCACHE_SPACE
          value: "4"
      modelFormat:
        name: vLLM
      name: qwen3-reranker
      resources:
        limits:
          cpu: "12"
          memory: 20Gi
        requests:
          cpu: "8"
          memory: 16Gi
      runtime: qwen3-reranker
      storageUri: "oci://quay.io/asoliman/qwen3-reranker-0.6b-seq-cls-modelcar:latest"
